export const LOGIN = 'LOGIN';
export const SIGNUP = 'SIGNUP';
export const EXPIRE = {
  IN: 'IN',
  AT: 'AT'
};
export const CARD_TYPE = {
  COUPON: 'COUPON',
  COUPON_TO: 'COUPON_TO',
  LIST: 'LIST',
  IMPORT: 'IMPORT',
  LIST_FROM: 'LIST_FROM',
  LIST_TO: 'LIST_TO'
};

export const COUPON_STATUS = {
  NOT_USED: 'NOT_USED',
  REQUESTED: 'REQUESTED',
  USED: 'USED'
};

export const LIST_STATUS = {
  PENDING: 'PENDING',
  ACTIVATED: 'ACTIVATED',
  REQUESTED: 'REQUESTED',
  DELETED: 'DELETED'
};

export const ALERT_TYPE = {
  REQUESTED: 'REQUESTED',
  CONFIRMED: 'CONFIRMED',
  DELETED: 'DELETED'
}
